---
title: "prescription rate and overdose mortality correlation"
author: "NAudi"
date: "August 8, 2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include= FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## Understanding the correlation between opioids prescription rate and drug overdose morality rate on county level

```{r }
#open needed libraries 
library(tidyverse)
library(readxl)

```

```{r, echo= FALSE}
# import opioid prescription rate tables 

presrate_2016 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
      sheet = "2016")

presrate_2015 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2015", col_types = c("text", 
         "text", "numeric", "numeric", "numeric"))

presrate_2014 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
                            sheet = "2014",
    col_types = c("text", "text", "numeric", 
        "numeric", "numeric"))

presrate_2013 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2013", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2012 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2012", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2011 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2011", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2010 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2010", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2009 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2009", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2008 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2008", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2007 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2007", col_types = c("text", 
        "text", "numeric", "numeric", "numeric"))

presrate_2006 <- read_excel("data/prescription_rate_per_county_2006_2016.xlsx", 
    sheet = "2006", col_types = c("text", 
        "text", "numeric", "numeric", "numeric")) 
```

```{r}
# combine tables 
presrate_2006_2016 <- bind_rows(presrate_2006, presrate_2007, presrate_2008, presrate_2009, presrate_2010, presrate_2011, presrate_2012, presrate_2013, presrate_2014, presrate_2015, presrate_2016)

# only rows with complete data
presrate_2006_2016 <-  presrate_2006_2016 [complete.cases(presrate_2006_2016), ]

#change column names to match overdose mortality table

names(presrate_2006_2016)[names(presrate_2006_2016)=="FIPS County Code"] <- "FIPS"
names(presrate_2006_2016)[names(presrate_2006_2016)=="County"] <- "county"

colnames(presrate_2006_2016)

```

```{r}
# import overdose mortality rates (per 100 0000), 
                #  lower side of the mortality rate range is a text, problem with values recorded as "<2". 
overdose_mortality <- read_excel("data/NCHS_-_Drug_Poisoning_Mortality_by_County__United_States.xlsx", 
    col_types = c("numeric", "numeric", "text", 
        "numeric", "text", "numeric", "text", 
        "numeric"))
overdose_mortality_complete <-  overdose_mortality[complete.cases(overdose_mortality), ]
```

```{r}
#join the both tables. PS: only rows with complete data. this yielded 30801 obs / 11 years = 2800 counties out oll all US 3007 counties. 
joined <- merge( presrate_2006_2016, overdose_mortality, by = c( "FIPS" , "year" ))

colnames(joined)[10] <- "lower"
colnames(joined)[11] <- "upper" 

#export table into CSV file
write_excel_csv(x = joined, path = "data/clean_merged_mortality_presrate.csv")
```

```{r}

plot(as.numeric(upper) ~ prescription_rate_per100, joined, subset = year == 2015)


```



