---
title: "pain related studies"
author: "NAudi"
date: "August 15, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, messages = FALSE)
```

## How much research related to opioids , pain have been going

```{r}
#open needed libraries
library(tidyverse)
library(readxl)

```

```{r}
# import data tables 

pain_studies <- read_csv("data/pain related studies, clinicaltrials.gov.csv", 
           col_types = cols(`Completion Date` = col_date(format = "%Y-%m-%d"), 
          `First Posted` = col_date(format = "%Y-%m-%d"), 
          `Last Update Posted` = col_date(format = "%Y-%m-%d"), 
          `Primary Completion Date` = col_date(format = "%Y-%m-%d"), 
          `Results First Posted` = col_date(format = "%Y-%m-%d"), 
          `Start Date` = col_date(format = "%Y-%m-%d"), 
          X28 = col_skip()))
# Droping addetional columns 
pain_studies<- pain_studies[, -c(28:731)]

```

```{r}
# graph the number of trials over time

PainPerYear <- pain_studies %>%
  mutate(start_year = format(pain_studies$`Start Date`, "%Y")) %>%
                            group_by(start_year) %>%
  summarise(total = n())

  PainPerYear_graph <- ggplot(data = PainPerYear, aes( x = start_year, y = total)) +
    geom_col() + xlab("Start Year") + ylab("Total Number of Trials") +
    ggtitle(" Clinical trials related to pain per year 1977-2020") +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text=element_text(size=6)) +
    geom_label(aes( label = total), size = 2) +
    labs(caption = "Source: www.clinicaltrials.gov, Data retrieved on 2018-08-15")
  ggsave("plot1.png", width = 14, height = 8)
  PainPerYear_graph

```

```{r}
#looking into condition targeted by trials per year 

ConditionPerYear <- pain_studies %>%
  mutate(start_year = format(pain_studies$`Start Date`, "%Y")) %>%
  group_by( Conditions, start_year) %>%
  summarise(Conditions_total = n()) %>%
  group_by(start_year) %>%
  mutate(start_year_total = n()) %>%
  ungroup() %>%
  filter( start_year >= 2005 , Conditions_total >= 3)


ConditionPerYear_graph <- ggplot(data = ConditionPerYear, aes(start_year ,
                                                               ConditionPerYear$Conditions)) +
  geom_count(aes( size = stat(prop), group = Conditions_total, color =  ConditionPerYear$Conditions ), show.legend = F) + 
 scale_size_area(max_size = 10) +
  theme(plot.title = element_text(hjust = 0.5),
          axis.text=element_text(size=5)) 
ggsave("plot2.png", width = 14, height = 8)
ConditionPerYear_graph

```

